// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.2
// source: proto/tiktok.proto

package chataggr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data structure from im/fetch/ response
type WebcastResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Messages          []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Cursor            string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	FetchInterval     int32                  `protobuf:"varint,3,opt,name=fetchInterval,proto3" json:"fetchInterval,omitempty"`
	ServerTimestamp   int64                  `protobuf:"varint,4,opt,name=serverTimestamp,proto3" json:"serverTimestamp,omitempty"`
	InternalExt       string                 `protobuf:"bytes,5,opt,name=internalExt,proto3" json:"internalExt,omitempty"`
	FetchType         int32                  `protobuf:"varint,6,opt,name=fetchType,proto3" json:"fetchType,omitempty"` // ws (1) or polling (2)
	WsParams          []*WebsocketParam      `protobuf:"bytes,7,rep,name=wsParams,proto3" json:"wsParams,omitempty"`
	HeartbeatDuration int32                  `protobuf:"varint,8,opt,name=heartbeatDuration,proto3" json:"heartbeatDuration,omitempty"`
	NeedAck           bool                   `protobuf:"varint,9,opt,name=needAck,proto3" json:"needAck,omitempty"`
	WsUrl             string                 `protobuf:"bytes,10,opt,name=wsUrl,proto3" json:"wsUrl,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WebcastResponse) Reset() {
	*x = WebcastResponse{}
	mi := &file_proto_tiktok_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastResponse) ProtoMessage() {}

func (x *WebcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastResponse.ProtoReflect.Descriptor instead.
func (*WebcastResponse) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{0}
}

func (x *WebcastResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *WebcastResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *WebcastResponse) GetFetchInterval() int32 {
	if x != nil {
		return x.FetchInterval
	}
	return 0
}

func (x *WebcastResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *WebcastResponse) GetInternalExt() string {
	if x != nil {
		return x.InternalExt
	}
	return ""
}

func (x *WebcastResponse) GetFetchType() int32 {
	if x != nil {
		return x.FetchType
	}
	return 0
}

func (x *WebcastResponse) GetWsParams() []*WebsocketParam {
	if x != nil {
		return x.WsParams
	}
	return nil
}

func (x *WebcastResponse) GetHeartbeatDuration() int32 {
	if x != nil {
		return x.HeartbeatDuration
	}
	return 0
}

func (x *WebcastResponse) GetNeedAck() bool {
	if x != nil {
		return x.NeedAck
	}
	return false
}

func (x *WebcastResponse) GetWsUrl() string {
	if x != nil {
		return x.WsUrl
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Binary        []byte                 `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_tiktok_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

type WebsocketParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketParam) Reset() {
	*x = WebsocketParam{}
	mi := &file_proto_tiktok_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketParam) ProtoMessage() {}

func (x *WebsocketParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketParam.ProtoReflect.Descriptor instead.
func (*WebsocketParam) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{2}
}

func (x *WebsocketParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebsocketParam) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_tiktok_proto protoreflect.FileDescriptor

var file_proto_tiktok_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x6b, 0x74, 0x6f, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x22, 0xf8, 0x02, 0x0a,
	0x0f, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2b, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x65, 0x74, 0x63, 0x68, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x66, 0x65,
	0x74, 0x63, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x0f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x45, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x45, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x65, 0x74, 0x63, 0x68,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x65, 0x74, 0x63,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x77, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b,
	0x2e, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52,
	0x08, 0x77, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x65, 0x64, 0x41,
	0x63, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6e, 0x65, 0x65, 0x64, 0x41, 0x63,
	0x6b, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x73, 0x55, 0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x77, 0x73, 0x55, 0x72, 0x6c, 0x22, 0x35, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x3a,
	0x0a, 0x0e, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x63, 0x68, 0x61, 0x74, 0x61, 0x67, 0x67, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_tiktok_proto_rawDescOnce sync.Once
	file_proto_tiktok_proto_rawDescData = file_proto_tiktok_proto_rawDesc
)

func file_proto_tiktok_proto_rawDescGZIP() []byte {
	file_proto_tiktok_proto_rawDescOnce.Do(func() {
		file_proto_tiktok_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tiktok_proto_rawDescData)
	})
	return file_proto_tiktok_proto_rawDescData
}

var file_proto_tiktok_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_tiktok_proto_goTypes = []any{
	(*WebcastResponse)(nil), // 0: TikTok.WebcastResponse
	(*Message)(nil),         // 1: TikTok.Message
	(*WebsocketParam)(nil),  // 2: TikTok.WebsocketParam
}
var file_proto_tiktok_proto_depIdxs = []int32{
	1, // 0: TikTok.WebcastResponse.messages:type_name -> TikTok.Message
	2, // 1: TikTok.WebcastResponse.wsParams:type_name -> TikTok.WebsocketParam
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tiktok_proto_init() }
func file_proto_tiktok_proto_init() {
	if File_proto_tiktok_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tiktok_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tiktok_proto_goTypes,
		DependencyIndexes: file_proto_tiktok_proto_depIdxs,
		MessageInfos:      file_proto_tiktok_proto_msgTypes,
	}.Build()
	File_proto_tiktok_proto = out.File
	file_proto_tiktok_proto_rawDesc = nil
	file_proto_tiktok_proto_goTypes = nil
	file_proto_tiktok_proto_depIdxs = nil
}
